# Generated by Django 5.0.7 on 2024-11-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeposition",
            name="employee_position_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
    ]
