# Generated by Django 5.0.7 on 2024-11-11 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_employeeposition_employee_position_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default=uuid.uuid4),
        ),
    ]
